server:
  port: 8080 # optional: picks free port automatically

spring:
  config:
    activate:
      on-profile: dev

  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: products
          uri: lb://product-service
          predicates:
            - Path=/products/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
