server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: products
          uri: lb://product-service
          predicates:
            - Path=/products/**
      default-filters:
        - name: DedupeResponseHeader
          args:
            Access-Control-Allow-Credentials: RETAIN_FIRST
            Access-Control-Allow-Origin: RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
